(function(d){function m(){this.regional=[];this.regional[""]={currentText:"Now",closeText:"Done",ampm:false,amNames:["AM","A"],pmNames:["PM","P"],timeFormat:"hh:mm tt",timeSuffix:"",timeOnlyTitle:"Choose Time",timeText:"Time",hourText:"Hour",minuteText:"Minute",secondText:"Second",millisecText:"Millisecond",timezoneText:"Time Zone"};this._defaults={showButtonPanel:true,timeOnly:false,showHour:true,showMinute:true,showSecond:false,showMillisec:false,showTimezone:false,showTime:true,stepHour:1,stepMinute:1,
stepSecond:1,stepMillisec:1,hour:0,minute:0,second:0,millisec:0,timezone:null,useLocalTimezone:false,defaultTimezone:"+0000",hourMin:0,minuteMin:0,secondMin:0,millisecMin:0,hourMax:23,minuteMax:59,secondMax:59,millisecMax:999,minDateTime:null,maxDateTime:null,onSelect:null,hourGrid:0,minuteGrid:0,secondGrid:0,millisecGrid:0,alwaysSetTime:true,separator:" ",altFieldTimeOnly:true,showTimepicker:true,timezoneIso8601:false,timezoneList:null,addSliderAccess:false,sliderAccessArgs:null};d.extend(this._defaults,
this.regional[""])}function r(b,a){d.extend(b,a);for(var c in a)if(a[c]===null||a[c]===void 0)b[c]=a[c];return b}d.ui.timepicker=d.ui.timepicker||{};if(!d.ui.timepicker.version){d.extend(d.ui,{timepicker:{version:"1.0.1"}});d.extend(m.prototype,{$input:null,$altInput:null,$timeObj:null,inst:null,hour_slider:null,minute_slider:null,second_slider:null,millisec_slider:null,timezone_select:null,hour:0,minute:0,second:0,millisec:0,timezone:null,defaultTimezone:"+0000",hourMinOriginal:null,minuteMinOriginal:null,
secondMinOriginal:null,millisecMinOriginal:null,hourMaxOriginal:null,minuteMaxOriginal:null,secondMaxOriginal:null,millisecMaxOriginal:null,ampm:"",formattedDate:"",formattedTime:"",formattedDateTime:"",timezoneList:null,setDefaults:function(b){r(this._defaults,b||{});return this},_newInst:function(b,a){var c=new m,e={},f;for(f in this._defaults){var g=b.attr("time:"+f);if(g)try{e[f]=eval(g)}catch(l){e[f]=g}}c._defaults=d.extend({},this._defaults,e,a,{beforeShow:function(b,e){if(d.isFunction(a.beforeShow))return a.beforeShow(b,
e,c)},onChangeMonthYear:function(e,f,g){c._updateDateTime(g);d.isFunction(a.onChangeMonthYear)&&a.onChangeMonthYear.call(b[0],e,f,g,c)},onClose:function(e,f){c.timeDefined===true&&b.val()!==""&&c._updateDateTime(f);d.isFunction(a.onClose)&&a.onClose.call(b[0],e,f,c)},timepicker:c});c.amNames=d.map(c._defaults.amNames,function(a){return a.toUpperCase()});c.pmNames=d.map(c._defaults.pmNames,function(a){return a.toUpperCase()});if(c._defaults.timezoneList===null){e=[];for(f=-11;f<=12;f++)e.push((f>=
0?"+":"-")+("0"+Math.abs(f).toString()).slice(-2)+"00");c._defaults.timezoneIso8601&&(e=d.map(e,function(a){return a=="+0000"?"Z":a.substring(0,3)+":"+a.substring(3)}));c._defaults.timezoneList=e}c.timezone=c._defaults.timezone;c.hour=c._defaults.hour;c.minute=c._defaults.minute;c.second=c._defaults.second;c.millisec=c._defaults.millisec;c.ampm="";c.$input=b;if(a.altField)c.$altInput=d(a.altField).css({cursor:"pointer"}).focus(function(){b.trigger("focus")});if(c._defaults.minDate===0||c._defaults.minDateTime===
0)c._defaults.minDate=new Date;if(c._defaults.maxDate===0||c._defaults.maxDateTime===0)c._defaults.maxDate=new Date;if(c._defaults.minDate!==void 0&&c._defaults.minDate instanceof Date)c._defaults.minDateTime=new Date(c._defaults.minDate.getTime());if(c._defaults.minDateTime!==void 0&&c._defaults.minDateTime instanceof Date)c._defaults.minDate=new Date(c._defaults.minDateTime.getTime());if(c._defaults.maxDate!==void 0&&c._defaults.maxDate instanceof Date)c._defaults.maxDateTime=new Date(c._defaults.maxDate.getTime());
if(c._defaults.maxDateTime!==void 0&&c._defaults.maxDateTime instanceof Date)c._defaults.maxDate=new Date(c._defaults.maxDateTime.getTime());return c},_addTimePicker:function(b){this.timeDefined=this._parseTime(this.$altInput&&this._defaults.altFieldTimeOnly?this.$input.val()+" "+this.$altInput.val():this.$input.val());this._limitMinMaxDateTime(b,false);this._injectTimePicker()},_parseTime:function(b,a){if(!this.inst)this.inst=d.datepicker._getInst(this.$input[0]);if(a||!this._defaults.timeOnly){var c=
d.datepicker._get(this.inst,"dateFormat");try{var e=u(c,this._defaults.timeFormat,b,d.datepicker._getFormatConfig(this.inst),this._defaults);if(!e.timeObj)return false;d.extend(this,e.timeObj)}catch(f){return false}}else{c=d.datepicker.parseTime(this._defaults.timeFormat,b,this._defaults);if(!c)return false;d.extend(this,c)}return true},_injectTimePicker:function(){var b=this.inst.dpDiv,a=this._defaults,c=this,e=parseInt(a.hourMax-(a.hourMax-a.hourMin)%a.stepHour,10),f=parseInt(a.minuteMax-(a.minuteMax-
a.minuteMin)%a.stepMinute,10),g=parseInt(a.secondMax-(a.secondMax-a.secondMin)%a.stepSecond,10),l=parseInt(a.millisecMax-(a.millisecMax-a.millisecMin)%a.stepMillisec,10),h=this.inst.id.toString().replace(/([^A-Za-z0-9_])/g,"");if(b.find("div#ui-timepicker-div-"+h).length===0&&a.showTimepicker){var i='<div class="ui-timepicker-div" id="ui-timepicker-div-'+h+'"><dl><dt class="ui_tpicker_time_label" id="ui_tpicker_time_label_'+h+'"'+(a.showTime?"":' style="display:none;"')+">"+a.timeText+'</dt><dd class="ui_tpicker_time" id="ui_tpicker_time_'+
h+'"'+(a.showTime?"":' style="display:none;"')+'></dd><dt class="ui_tpicker_hour_label" id="ui_tpicker_hour_label_'+h+'"'+(a.showHour?"":' style="display:none;"')+">"+a.hourText+"</dt>",s=0,p=0,o=0,m=0,n=null;i+='<dd class="ui_tpicker_hour"><div id="ui_tpicker_hour_'+h+'"'+(a.showHour?"":' style="display:none;"')+"></div>";if(a.showHour&&a.hourGrid>0){i+='<div style="padding-left: 1px"><table class="ui-tpicker-grid-label"><tr>';for(var j=a.hourMin;j<=e;j+=parseInt(a.hourGrid,10)){s++;var q=a.ampm&&
j>12?j-12:j;q<10&&(q="0"+q);a.ampm&&(j===0?q="12a":q+=j<12?"a":"p");i+="<td>"+q+"</td>"}i+="</tr></table></div>"}i+="</dd>";i+='<dt class="ui_tpicker_minute_label" id="ui_tpicker_minute_label_'+h+'"'+(a.showMinute?"":' style="display:none;"')+">"+a.minuteText+'</dt><dd class="ui_tpicker_minute"><div id="ui_tpicker_minute_'+h+'"'+(a.showMinute?"":' style="display:none;"')+"></div>";if(a.showMinute&&a.minuteGrid>0){i+='<div style="padding-left: 1px"><table class="ui-tpicker-grid-label"><tr>';for(j=
a.minuteMin;j<=f;j+=parseInt(a.minuteGrid,10))p++,i+="<td>"+(j<10?"0":"")+j+"</td>";i+="</tr></table></div>"}i+="</dd>";i+='<dt class="ui_tpicker_second_label" id="ui_tpicker_second_label_'+h+'"'+(a.showSecond?"":' style="display:none;"')+">"+a.secondText+'</dt><dd class="ui_tpicker_second"><div id="ui_tpicker_second_'+h+'"'+(a.showSecond?"":' style="display:none;"')+"></div>";if(a.showSecond&&a.secondGrid>0){i+='<div style="padding-left: 1px"><table><tr>';for(j=a.secondMin;j<=g;j+=parseInt(a.secondGrid,
10))o++,i+="<td>"+(j<10?"0":"")+j+"</td>";i+="</tr></table></div>"}i+="</dd>";i+='<dt class="ui_tpicker_millisec_label" id="ui_tpicker_millisec_label_'+h+'"'+(a.showMillisec?"":' style="display:none;"')+">"+a.millisecText+'</dt><dd class="ui_tpicker_millisec"><div id="ui_tpicker_millisec_'+h+'"'+(a.showMillisec?"":' style="display:none;"')+"></div>";if(a.showMillisec&&a.millisecGrid>0){i+='<div style="padding-left: 1px"><table><tr>';for(j=a.millisecMin;j<=l;j+=parseInt(a.millisecGrid,10))m++,i+="<td>"+
(j<10?"0":"")+j+"</td>";i+="</tr></table></div>"}i+="</dd>";i+='<dt class="ui_tpicker_timezone_label" id="ui_tpicker_timezone_label_'+h+'"'+(a.showTimezone?"":' style="display:none;"')+">"+a.timezoneText+"</dt>";i+='<dd class="ui_tpicker_timezone" id="ui_tpicker_timezone_'+h+'"'+(a.showTimezone?"":' style="display:none;"')+"></dd>";i+="</dl></div>";var k=d(i);a.timeOnly===true&&(k.prepend('<div class="ui-widget-header ui-helper-clearfix ui-corner-all"><div class="ui-datepicker-title">'+a.timeOnlyTitle+
"</div></div>"),b.find(".ui-datepicker-header, .ui-datepicker-calendar").hide());this.hour_slider=k.find("#ui_tpicker_hour_"+h).slider({orientation:"horizontal",value:this.hour,min:a.hourMin,max:e,step:a.stepHour,slide:function(a,b){c.hour_slider.slider("option","value",b.value);c._onTimeChange()}});this.minute_slider=k.find("#ui_tpicker_minute_"+h).slider({orientation:"horizontal",value:this.minute,min:a.minuteMin,max:f,step:a.stepMinute,slide:function(a,b){c.minute_slider.slider("option","value",
b.value);c._onTimeChange()}});this.second_slider=k.find("#ui_tpicker_second_"+h).slider({orientation:"horizontal",value:this.second,min:a.secondMin,max:g,step:a.stepSecond,slide:function(a,b){c.second_slider.slider("option","value",b.value);c._onTimeChange()}});this.millisec_slider=k.find("#ui_tpicker_millisec_"+h).slider({orientation:"horizontal",value:this.millisec,min:a.millisecMin,max:l,step:a.stepMillisec,slide:function(a,b){c.millisec_slider.slider("option","value",b.value);c._onTimeChange()}});
this.timezone_select=k.find("#ui_tpicker_timezone_"+h).append("<select></select>").find("select");d.fn.append.apply(this.timezone_select,d.map(a.timezoneList,function(a){return d("<option />").val(typeof a=="object"?a.value:a).text(typeof a=="object"?a.label:a)}));typeof this.timezone!="undefined"&&this.timezone!==null&&this.timezone!==""?v(new Date(this.inst.selectedYear,this.inst.selectedMonth,this.inst.selectedDay,12))==this.timezone?t(c):this.timezone_select.val(this.timezone):typeof this.hour!=
"undefined"&&this.hour!==null&&this.hour!==""?this.timezone_select.val(a.defaultTimezone):t(c);this.timezone_select.change(function(){c._defaults.useLocalTimezone=false;c._onTimeChange()});a.showHour&&a.hourGrid>0&&(n=100*s*a.hourGrid/(e-a.hourMin),k.find(".ui_tpicker_hour table").css({width:n+"%",marginLeft:n/(-2*s)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){var b=d(this).html();if(a.ampm)var e=b.substring(2).toLowerCase(),b=parseInt(b.substring(0,2),10),
b=e=="a"?b==12?0:b:b==12?12:b+12;c.hour_slider.slider("option","value",b);c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",width:100/s+"%",textAlign:"center",overflow:"hidden"})}));a.showMinute&&a.minuteGrid>0&&(n=100*p*a.minuteGrid/(f-a.minuteMin),k.find(".ui_tpicker_minute table").css({width:n+"%",marginLeft:n/(-2*p)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){c.minute_slider.slider("option","value",d(this).html());c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",
width:100/p+"%",textAlign:"center",overflow:"hidden"})}));a.showSecond&&a.secondGrid>0&&k.find(".ui_tpicker_second table").css({width:n+"%",marginLeft:n/(-2*o)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){c.second_slider.slider("option","value",d(this).html());c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",width:100/o+"%",textAlign:"center",overflow:"hidden"})});a.showMillisec&&a.millisecGrid>0&&k.find(".ui_tpicker_millisec table").css({width:n+
"%",marginLeft:n/(-2*m)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){c.millisec_slider.slider("option","value",d(this).html());c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",width:100/m+"%",textAlign:"center",overflow:"hidden"})});e=b.find(".ui-datepicker-buttonpane");e.length?e.before(k):b.append(k);this.$timeObj=k.find("#ui_tpicker_time_"+h);if(this.inst!==null)b=this.timeDefined,this._onTimeChange(),this.timeDefined=b;b=function(){c._onSelectHandler()};
this.hour_slider.bind("slidestop",b);this.minute_slider.bind("slidestop",b);this.second_slider.bind("slidestop",b);this.millisec_slider.bind("slidestop",b);if(this._defaults.addSliderAccess){var r=this._defaults.sliderAccessArgs;setTimeout(function(){if(k.find(".ui-slider-access").length===0){k.find(".ui-slider:visible").sliderAccess(r);var a=k.find(".ui-slider-access:eq(0)").outerWidth(true);a&&k.find("table:visible").each(function(){var b=d(this),c=b.outerWidth(),e=b.css("marginLeft").toString().replace("%",
""),f=c-a;b.css({width:f,marginLeft:e*f/c+"%"})})}},0)}}},_limitMinMaxDateTime:function(b,a){var c=this._defaults,e=new Date(b.selectedYear,b.selectedMonth,b.selectedDay);if(this._defaults.showTimepicker){if(d.datepicker._get(b,"minDateTime")!==null&&d.datepicker._get(b,"minDateTime")!==void 0&&e){var f=d.datepicker._get(b,"minDateTime"),g=new Date(f.getFullYear(),f.getMonth(),f.getDate(),0,0,0,0);if(this.hourMinOriginal===null||this.minuteMinOriginal===null||this.secondMinOriginal===null||this.millisecMinOriginal===
null)this.hourMinOriginal=c.hourMin,this.minuteMinOriginal=c.minuteMin,this.secondMinOriginal=c.secondMin,this.millisecMinOriginal=c.millisecMin;if(b.settings.timeOnly||g.getTime()==e.getTime())if(this._defaults.hourMin=f.getHours(),this.hour<=this._defaults.hourMin)if(this.hour=this._defaults.hourMin,this._defaults.minuteMin=f.getMinutes(),this.minute<=this._defaults.minuteMin)this.minute=this._defaults.minuteMin,this._defaults.secondMin=f.getSeconds();else if(this.second<=this._defaults.secondMin)this.second=
this._defaults.secondMin,this._defaults.millisecMin=f.getMilliseconds();else{if(this.millisec<this._defaults.millisecMin)this.millisec=this._defaults.millisecMin;this._defaults.millisecMin=this.millisecMinOriginal}else this._defaults.minuteMin=this.minuteMinOriginal,this._defaults.secondMin=this.secondMinOriginal,this._defaults.millisecMin=this.millisecMinOriginal;else this._defaults.hourMin=this.hourMinOriginal,this._defaults.minuteMin=this.minuteMinOriginal,this._defaults.secondMin=this.secondMinOriginal,
this._defaults.millisecMin=this.millisecMinOriginal}if(d.datepicker._get(b,"maxDateTime")!==null&&d.datepicker._get(b,"maxDateTime")!==void 0&&e){f=d.datepicker._get(b,"maxDateTime");g=new Date(f.getFullYear(),f.getMonth(),f.getDate(),0,0,0,0);if(this.hourMaxOriginal===null||this.minuteMaxOriginal===null||this.secondMaxOriginal===null)this.hourMaxOriginal=c.hourMax,this.minuteMaxOriginal=c.minuteMax,this.secondMaxOriginal=c.secondMax,this.millisecMaxOriginal=c.millisecMax;if(b.settings.timeOnly||
g.getTime()==e.getTime())if(this._defaults.hourMax=f.getHours(),this.hour>=this._defaults.hourMax)if(this.hour=this._defaults.hourMax,this._defaults.minuteMax=f.getMinutes(),this.minute>=this._defaults.minuteMax)this.minute=this._defaults.minuteMax,this._defaults.secondMax=f.getSeconds();else if(this.second>=this._defaults.secondMax)this.second=this._defaults.secondMax,this._defaults.millisecMax=f.getMilliseconds();else{if(this.millisec>this._defaults.millisecMax)this.millisec=this._defaults.millisecMax;
this._defaults.millisecMax=this.millisecMaxOriginal}else this._defaults.minuteMax=this.minuteMaxOriginal,this._defaults.secondMax=this.secondMaxOriginal,this._defaults.millisecMax=this.millisecMaxOriginal;else this._defaults.hourMax=this.hourMaxOriginal,this._defaults.minuteMax=this.minuteMaxOriginal,this._defaults.secondMax=this.secondMaxOriginal,this._defaults.millisecMax=this.millisecMaxOriginal}a!==void 0&&a===true&&(c=parseInt(this._defaults.hourMax-(this._defaults.hourMax-this._defaults.hourMin)%
this._defaults.stepHour,10),e=parseInt(this._defaults.minuteMax-(this._defaults.minuteMax-this._defaults.minuteMin)%this._defaults.stepMinute,10),f=parseInt(this._defaults.secondMax-(this._defaults.secondMax-this._defaults.secondMin)%this._defaults.stepSecond,10),g=parseInt(this._defaults.millisecMax-(this._defaults.millisecMax-this._defaults.millisecMin)%this._defaults.stepMillisec,10),this.hour_slider&&this.hour_slider.slider("option",{min:this._defaults.hourMin,max:c}).slider("value",this.hour),
this.minute_slider&&this.minute_slider.slider("option",{min:this._defaults.minuteMin,max:e}).slider("value",this.minute),this.second_slider&&this.second_slider.slider("option",{min:this._defaults.secondMin,max:f}).slider("value",this.second),this.millisec_slider&&this.millisec_slider.slider("option",{min:this._defaults.millisecMin,max:g}).slider("value",this.millisec))}},_onTimeChange:function(){var b=this.hour_slider?this.hour_slider.slider("value"):false,a=this.minute_slider?this.minute_slider.slider("value"):
false,c=this.second_slider?this.second_slider.slider("value"):false,e=this.millisec_slider?this.millisec_slider.slider("value"):false,f=this.timezone_select?this.timezone_select.val():false,g=this._defaults;typeof b=="object"&&(b=false);typeof a=="object"&&(a=false);typeof c=="object"&&(c=false);typeof e=="object"&&(e=false);typeof f=="object"&&(f=false);b!==false&&(b=parseInt(b,10));a!==false&&(a=parseInt(a,10));c!==false&&(c=parseInt(c,10));e!==false&&(e=parseInt(e,10));var l=g[b<12?"amNames":"pmNames"][0],
h=b!=this.hour||a!=this.minute||c!=this.second||e!=this.millisec||this.ampm.length>0&&b<12!=(d.inArray(this.ampm.toUpperCase(),this.amNames)!==-1)||f!=this.timezone;if(h){if(b!==false)this.hour=b;if(a!==false)this.minute=a;if(c!==false)this.second=c;if(e!==false)this.millisec=e;if(f!==false)this.timezone=f;if(!this.inst)this.inst=d.datepicker._getInst(this.$input[0]);this._limitMinMaxDateTime(this.inst,true)}if(g.ampm)this.ampm=l;this.formattedTime=d.datepicker.formatTime(this._defaults.timeFormat,
this,this._defaults);this.$timeObj&&this.$timeObj.text(this.formattedTime+g.timeSuffix);this.timeDefined=true;h&&this._updateDateTime()},_onSelectHandler:function(){var b=this._defaults.onSelect,a=this.$input?this.$input[0]:null;b&&a&&b.apply(a,[this.formattedDateTime,this])},_formatTime:function(b,a){var b=b||{hour:this.hour,minute:this.minute,second:this.second,millisec:this.millisec,ampm:this.ampm,timezone:this.timezone},c=(a||this._defaults.timeFormat).toString(),c=d.datepicker.formatTime(c,b,
this._defaults);if(arguments.length)return c;else this.formattedTime=c},_updateDateTime:function(b){var b=this.inst||b,a=d.datepicker._daylightSavingAdjust(new Date(b.selectedYear,b.selectedMonth,b.selectedDay)),c=d.datepicker._get(b,"dateFormat"),e=d.datepicker._getFormatConfig(b),b=a!==null&&this.timeDefined,a=this.formattedDate=d.datepicker.formatDate(c,a===null?new Date:a,e);if(this._defaults.timeOnly===true)a=this.formattedTime;else if(this._defaults.timeOnly!==true&&(this._defaults.alwaysSetTime||
b))a+=this._defaults.separator+this.formattedTime+this._defaults.timeSuffix;this.formattedDateTime=a;this._defaults.showTimepicker?this.$altInput&&this._defaults.altFieldTimeOnly===true?(this.$altInput.val(this.formattedTime),this.$input.val(this.formattedDate)):(this.$altInput&&this.$altInput.val(a),this.$input.val(a)):this.$input.val(this.formattedDate);this.$input.trigger("change")}});d.fn.extend({timepicker:function(b){var b=b||{},a=arguments;typeof b=="object"&&(a[0]=d.extend(b,{timeOnly:true}));
return d(this).each(function(){d.fn.datetimepicker.apply(d(this),a)})},datetimepicker:function(b){var b=b||{},a=arguments;return typeof b=="string"?b=="getDate"?d.fn.datepicker.apply(d(this[0]),a):this.each(function(){var b=d(this);b.datepicker.apply(b,a)}):this.each(function(){var a=d(this);a.datepicker(d.timepicker._newInst(a,b)._defaults)})}});d.datepicker.parseDateTime=function(b,a,c,e,d){b=u(b,a,c,e,d);if(b.timeObj)a=b.timeObj,b.date.setHours(a.hour,a.minute,a.second,a.millisec);return b.date};
d.datepicker.parseTime=function(b,a,c){var c=r(r({},d.timepicker._defaults),c||{}),e="^"+b.toString().replace(/h{1,2}/ig,"(\\d?\\d)").replace(/m{1,2}/ig,"(\\d?\\d)").replace(/s{1,2}/ig,"(\\d?\\d)").replace(/l{1}/ig,"(\\d?\\d?\\d)").replace(/t{1,2}/ig,function(a,b){var c=[];a&&d.merge(c,a);b&&d.merge(c,b);c=d.map(c,function(a){return a.replace(/[.*+?|()\[\]{}\\]/g,"\\$&")});return"("+c.join("|")+")?"}(c.amNames,c.pmNames)).replace(/z{1}/ig,"(z|[-+]\\d\\d:?\\d\\d)?").replace(/\s/g,"\\s?")+c.timeSuffix+
"$",b=function(a){var a=a.toLowerCase().match(/(h{1,2}|m{1,2}|s{1,2}|l{1}|t{1,2}|z)/g),b={h:-1,m:-1,s:-1,l:-1,t:-1,z:-1};if(a)for(var c=0;c<a.length;c++)b[a[c].toString().charAt(0)]==-1&&(b[a[c].toString().charAt(0)]=c+1);return b}(b),f="",e=a.match(RegExp(e,"i")),a={hour:0,minute:0,second:0,millisec:0};if(e){if(b.t!==-1)e[b.t]===void 0||e[b.t].length===0?(f="",a.ampm=""):(f=d.inArray(e[b.t],c.amNames)!==-1?"AM":"PM",a.ampm=c[f=="AM"?"amNames":"pmNames"][0]);if(b.h!==-1)a.hour=f=="AM"&&e[b.h]=="12"?
0:f=="PM"&&e[b.h]!="12"?parseInt(e[b.h],10)+12:Number(e[b.h]);if(b.m!==-1)a.minute=Number(e[b.m]);if(b.s!==-1)a.second=Number(e[b.s]);if(b.l!==-1)a.millisec=Number(e[b.l]);if(b.z!==-1&&e[b.z]!==void 0){b=e[b.z].toUpperCase();switch(b.length){case 1:b=c.timezoneIso8601?"Z":"+0000";break;case 5:c.timezoneIso8601&&(b=b.substring(1)=="0000"?"Z":b.substring(0,3)+":"+b.substring(3));break;case 6:c.timezoneIso8601?b.substring(1)=="00:00"&&(b="Z"):b=b=="Z"||b.substring(1)=="00:00"?"+0000":b.replace(/:/,"")}a.timezone=
b}return a}return false};d.datepicker.formatTime=function(b,a,c){var c=c||{},c=d.extend(d.timepicker._defaults,c),a=d.extend({hour:0,minute:0,second:0,millisec:0,timezone:"+0000"},a),e=c.amNames[0],f=parseInt(a.hour,10);c.ampm&&(f>11&&(e=c.pmNames[0],f>12&&(f%=12)),f===0&&(f=12));b=b.replace(/(?:hh?|mm?|ss?|[tT]{1,2}|[lz])/g,function(b){switch(b.toLowerCase()){case "hh":return("0"+f).slice(-2);case "h":return f;case "mm":return("0"+a.minute).slice(-2);case "m":return a.minute;case "ss":return("0"+
a.second).slice(-2);case "s":return a.second;case "l":return("00"+a.millisec).slice(-3);case "z":return a.timezone;case "t":case "tt":return c.ampm?(b.length==1&&(e=e.charAt(0)),b.charAt(0)=="T"?e.toUpperCase():e.toLowerCase()):""}});return b=d.trim(b)};d.datepicker._base_selectDate=d.datepicker._selectDate;d.datepicker._selectDate=function(b,a){var c=this._getInst(d(b)[0]),e=this._get(c,"timepicker");e?(e._limitMinMaxDateTime(c,true),c.inline=c.stay_open=true,this._base_selectDate(b,a),c.inline=
c.stay_open=false,this._notifyChange(c),this._updateDatepicker(c)):this._base_selectDate(b,a)};d.datepicker._base_updateDatepicker=d.datepicker._updateDatepicker;d.datepicker._updateDatepicker=function(b){var a=b.input[0];if(!d.datepicker._curInst||!(d.datepicker._curInst!=b&&d.datepicker._datepickerShowing&&d.datepicker._lastInput!=a))if(typeof b.stay_open!=="boolean"||b.stay_open===false)if(this._base_updateDatepicker(b),a=this._get(b,"timepicker"))a._addTimePicker(b),a._defaults.useLocalTimezone&&
(t(a,new Date(b.selectedYear,b.selectedMonth,b.selectedDay,12)),a._onTimeChange())};d.datepicker._base_doKeyPress=d.datepicker._doKeyPress;d.datepicker._doKeyPress=function(b){var a=d.datepicker._getInst(b.target),c=d.datepicker._get(a,"timepicker");if(c&&d.datepicker._get(a,"constrainInput")){var e=c._defaults.ampm,a=d.datepicker._possibleChars(d.datepicker._get(a,"dateFormat")),c=c._defaults.timeFormat.toString().replace(/[hms]/g,"").replace(/TT/g,e?"APM":"").replace(/Tt/g,e?"AaPpMm":"").replace(/tT/g,
e?"AaPpMm":"").replace(/T/g,e?"AP":"").replace(/tt/g,e?"apm":"").replace(/t/g,e?"ap":"")+" "+c._defaults.separator+c._defaults.timeSuffix+(c._defaults.showTimezone?c._defaults.timezoneList.join(""):"")+c._defaults.amNames.join("")+c._defaults.pmNames.join("")+a,e=String.fromCharCode(b.charCode===void 0?b.keyCode:b.charCode);return b.ctrlKey||e<" "||!a||c.indexOf(e)>-1}return d.datepicker._base_doKeyPress(b)};d.datepicker._base_doKeyUp=d.datepicker._doKeyUp;d.datepicker._doKeyUp=function(b){var a=
d.datepicker._getInst(b.target),c=d.datepicker._get(a,"timepicker");if(c&&c._defaults.timeOnly&&a.input.val()!=a.lastVal)try{d.datepicker._updateDatepicker(a)}catch(e){d.datepicker.log(e)}return d.datepicker._base_doKeyUp(b)};d.datepicker._base_gotoToday=d.datepicker._gotoToday;d.datepicker._gotoToday=function(b){var a=this._getInst(d(b)[0]),c=a.dpDiv;this._base_gotoToday(b);b=this._get(a,"timepicker");t(b);this._setTime(a,new Date);d(".ui-datepicker-today",c).click()};d.datepicker._disableTimepickerDatepicker=
function(b){var a=this._getInst(b);if(a){var c=this._get(a,"timepicker");d(b).datepicker("getDate");if(c)c._defaults.showTimepicker=false,c._updateDateTime(a)}};d.datepicker._enableTimepickerDatepicker=function(b){var a=this._getInst(b);if(a){var c=this._get(a,"timepicker");d(b).datepicker("getDate");if(c)c._defaults.showTimepicker=true,c._addTimePicker(a),c._updateDateTime(a)}};d.datepicker._setTime=function(b,a){var c=this._get(b,"timepicker");if(c){var e=c._defaults,d=a?a.getHours():e.hour,g=a?
a.getMinutes():e.minute,l=a?a.getSeconds():e.second,h=a?a.getMilliseconds():e.millisec,i=d===e.hourMin,m=g===e.minuteMin,p=l===e.secondMin,o=false;if(d<e.hourMin||d>e.hourMax)o=true;else if((g<e.minuteMin||g>e.minuteMax)&&i)o=true;else if((l<e.secondMin||l>e.secondMax)&&i&&m)o=true;else if((h<e.millisecMin||h>e.millisecMax)&&i&&m&&p)o=true;if(o)d=e.hourMin,g=e.minuteMin,l=e.secondMin,h=e.millisecMin;c.hour=d;c.minute=g;c.second=l;c.millisec=h;c.hour_slider&&c.hour_slider.slider("value",d);c.minute_slider&&
c.minute_slider.slider("value",g);c.second_slider&&c.second_slider.slider("value",l);c.millisec_slider&&c.millisec_slider.slider("value",h);c._onTimeChange();c._updateDateTime(b)}};d.datepicker._setTimeDatepicker=function(b,a,c){if(b=this._getInst(b)){var e=this._get(b,"timepicker");e&&(this._setDateFromField(b),a&&(typeof a=="string"?(e._parseTime(a,c),a=new Date,a.setHours(e.hour,e.minute,e.second,e.millisec)):a=new Date(a.getTime()),a.toString()=="Invalid Date"&&(a=void 0),this._setTime(b,a)))}};
d.datepicker._base_setDateDatepicker=d.datepicker._setDateDatepicker;d.datepicker._setDateDatepicker=function(b,a){var c=this._getInst(b);if(c){var e=a instanceof Date?new Date(a.getTime()):a;this._updateDatepicker(c);this._base_setDateDatepicker.apply(this,arguments);this._setTimeDatepicker(b,e,true)}};d.datepicker._base_getDateDatepicker=d.datepicker._getDateDatepicker;d.datepicker._getDateDatepicker=function(b,a){var c=this._getInst(b);if(c){var e=this._get(c,"timepicker");return e?(this._setDateFromField(c,
a),(c=this._getDate(c))&&e._parseTime(d(b).val(),e.timeOnly)&&c.setHours(e.hour,e.minute,e.second,e.millisec),c):this._base_getDateDatepicker(b,a)}};d.datepicker._base_parseDate=d.datepicker.parseDate;d.datepicker.parseDate=function(b,a,c){a=w(b,a,c);return d.datepicker._base_parseDate(b,a[0],c)};d.datepicker._base_formatDate=d.datepicker._formatDate;d.datepicker._formatDate=function(b){var a=this._get(b,"timepicker");return a?(a._updateDateTime(b),a.$input.val()):this._base_formatDate(b)};d.datepicker._base_optionDatepicker=
d.datepicker._optionDatepicker;d.datepicker._optionDatepicker=function(b,a,c){var e=this._getInst(b);if(!e)return null;if(e=this._get(e,"timepicker")){var d=null,g=null,l=null;if(typeof a=="string")a==="minDate"||a==="minDateTime"?d=c:a==="maxDate"||a==="maxDateTime"?g=c:a==="onSelect"&&(l=c);else if(typeof a=="object")if(a.minDate)d=a.minDate;else if(a.minDateTime)d=a.minDateTime;else if(a.maxDate)g=a.maxDate;else if(a.maxDateTime)g=a.maxDateTime;if(d)d=d===0?new Date:new Date(d),e._defaults.minDate=
d,e._defaults.minDateTime=d;else if(g)g=g===0?new Date:new Date(g),e._defaults.maxDate=g,e._defaults.maxDateTime=g;else if(l)e._defaults.onSelect=l}return c===void 0?this._base_optionDatepicker(b,a):this._base_optionDatepicker(b,a,c)};var w=function(b,a,c){try{d.datepicker._base_parseDate(b,a,c)}catch(e){if(e.indexOf(":")>=0)return b=a.length-(e.length-e.indexOf(":")-2),a.substring(b),[a.substring(0,b),a.substring(b)];else throw e;}return[a,""]},u=function(b,a,c,e,f){c=w(b,c,e);b=d.datepicker._base_parseDate(b,
c[0],e);if(c[1]!==""){e=c[1];c=f&&f.separator?f.separator:d.timepicker._defaults.separator;if(e.indexOf(c)!==0)throw"Missing time separator";e=e.substring(c.length);a=d.datepicker.parseTime(a,e,f);if(a===null)throw"Wrong time format";return{date:b,timeObj:a}}else return{date:b}},t=function(b,a){if(b&&b.timezone_select){b._defaults.useLocalTimezone=true;var c=v(typeof a!=="undefined"?a:new Date);b._defaults.timezoneIso8601&&(c=c.substring(0,3)+":"+c.substring(3));b.timezone_select.val(c)}},v=function(b){b=
b.getTimezoneOffset()*-10100/60;return(b>=0?"+":"-")+Math.abs(b).toString().substr(1)};d.timepicker=new m;d.timepicker.version="1.0.1"}})(jQuery);
